
CREATE TABLE IF NOT EXISTS EMPLOYEE ( firstName TEXT NOT NULL, 
lastName TEXT NOT NULL, 
employeeID INTEGER NOT NULL PRIMARY KEY,
position TEXT NOT NULL,
wage DOUBLE NOT NULL);

DELETE FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES ("Justin", "Lawrence", 95, "Manager", 24.00);