CREATE TABLE IF NOT EXISTS EMPLOYEE ( 
    firstName TEXT NOT NULL, 
    lastName TEXT NOT NULL, 
    employeeID INTEGER NOT NULL PRIMARY KEY,
    position TEXT NOT NULL,
    wage DOUBLE NOT NULL,
    tipOut DOUBLE 
);

CREATE TABLE IF NOT EXISTS PAYROLL (
    payrollID INTEGER PRIMARY KEY AUTOINCREMENT, 
    employeeID INTEGER NOT NULL,
    hours DOUBLE NOT NULL,
    dateStart DATE NOT NULL,
    dateEnd DATE NOT NULL,
    tips DOUBLE NOT NULL,
    FOREIGN KEY (employeeID) REFERENCES EMPLOYEE(employeeID)
);

CREATE TABLE IF NOT EXISTS TIPOUT (
    position TEXT NOT NULL PRIMARY KEY, 
    tipOut DOUBLE NOT NULL
);


DELETE FROM EMPLOYEE;
