
CREATE TABLE IF NOT EXISTS EMPLOYEE ( 
    firstName TEXT NOT NULL, 
    lastName TEXT NOT NULL, 
    employeeID INTEGER NOT NULL PRIMARY KEY,
    position TEXT NOT NULL,
    wage DOUBLE NOT NULL
);

DELETE FROM EMPLOYEE;

